name: Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.10.2

      - name: Install format dependencies
        run: |
          sudo apt install clang-format-10
          pip3 install cmakelang pyyaml

      - name: configure
        run: cmake -G Ninja -S test -B build

      - name: check style
        run: cmake --build build --target check-format
